export type Job = {
  role: string;
  org: string;
  location: string;
  period: string;
  bullets: string[];
};

export const EXPERIENCE: Job[] = [
  {
    role: "Vehicle Safety Operator, AV Test & Validation",
    org: "Avride (via HireArt)",
    location: "Austin, TX",
    period: "Apr 2026 — Present",
    bullets: [
      "Operate autonomous vehicles safely and lawfully, currently driving Golden Rides missions collecting pickup and drop-off (PUDO) data across downtown and north Austin",
      "Alternate between manual driving and supervising the vehicle in autonomous mode, working closely with remote operators throughout each shift",
      "Support data collection and in-field testing efforts, including adjusting hardware, uploading software, and assisting with basic technical troubleshooting",
      "Prepare vehicles daily for in-field operations, performing safety checks and confirming system readiness before every shift",
      "Monitor vehicle performance during on-road operations and submit detailed reports on system behavior, supporting system advancements and operational improvements",
      "Collaborate directly with engineers and operations leaders, providing field feedback and insight on system performance and environmental factors",
      "Maintain full alertness and anticipate hazards, driver errors, and unexpected events across extended shifts, applying thorough knowledge of local traffic regulations",
      "Actively completing certification to operate the vehicle in autonomous (AP) mode",
    ],
  },
  {
    role: "Validation Specialist / QA Test Engineer",
    org: "Join Parachute LLC",
    location: "Austin, TX",
    period: "Mar 2023 — Jul 2025",
    bullets: [
      "Owned the validation process end to end for SaMD (Software as a Medical Device) and regulated equipment, from opening the change request through scoping, drafting, pre-approval, execution, post-approval, and closeout",
      "Authored Validation Plans, IQ/OQ/PQ protocols, risk assessments, and Validation Summary Reports (VSR/FVSR) in compliance with FDA 21 CFR Part 11/820, ISO 13485, ISO 14971, and GAMP 5",
      "Executed comprehensive manual testing across regulated workflows, electronic records, and system interfaces, ensuring functional accuracy, data integrity, and compliance under both normal and edge-case conditions",
      "Qualified critical medical equipment including plasmapheresis machines, centrifuges, and refractometers through structured IQ/OQ/PQ protocols",
      "Managed deviations and CAPA workflows, conducting root cause analyses and implementing corrective actions to prevent recurrence and maintain audit readiness",
      "Maintained full traceability matrices from user requirements through functional requirements, test cases, and evidence to support regulatory inspections and internal quality audits",
      "Supported change control processes, performing impact assessments and regression validation for system and process updates",
      "Contributed to building a new regression test library for automated testing, working hands-on with Selenium and gaining exposure to Cypress and Playwright",
      "Leveraged AI (ChatGPT) to strengthen validation strategy, improving test scoping and accelerating automated test scripting while building the regression library",
      "Built an AI-driven template filler that auto-generated validation plans and project plans from a provided scope, reducing documentation time and improving consistency",
      "Designed and built a fully automated solution to track validation progress, test scripts, and test cases, giving the team real-time visibility into status and coverage",
      "Developed an equipment management system tracking device status (active, in-use, inactive, available), inventory, and lifecycle, with role-based user access and permissions",
      "Led validation of in-house enterprise systems including ERP and CRM platforms built on Power Apps and Dataverse, validating data integrity, user roles and permissions, workflows, and connectors",
      "Built Power BI dashboards and reports tracking validation metrics and quality data, establishing backend data connections from Snowflake for accurate, timely reporting",
    ],
  },
  {
    role: "Autopilot Software Test Operator",
    org: "Tesla",
    location: "Austin, TX",
    period: "Feb 2024 — Jun 2024",
    bullets: [
      "Drove engineering vehicles for extended daily sessions of 6 to 8 hours, collecting audio and camera data for Autopilot and Full Self-Driving (FSD) training and testing across real-world and controlled environments",
      "Operated and managed data recording devices per shift protocols, starting, stopping, and monitoring equipment throughout each session",
      "Performed minor software and hardware debugging as needed to keep test equipment operational",
      "Wrote detailed daily drive reports documenting observations, anomalies, and data quality issues to support engineering triage and feature improvement",
      "Logged a significant number of software anomalies across multiple structured test plans, contributing to measurable reductions in FSD disengagements and improved system stability",
      "Performed post-drive log reviews to identify behavioral regressions, data anomalies, and performance patterns across successive software builds",
      "Partnered with engineering teams to reproduce defects, validate firmware updates, and confirm fixes through targeted regression testing",
      "Provided feedback and process improvement suggestions to optimize data collection workflows",
    ],
  },
  {
    role: "Validation Specialist / Software QA Test Engineer",
    org: "Google",
    location: "Austin, TX",
    period: "Aug 2021 — Mar 2023",
    bullets: [
      "Designed and executed manual and exploratory functional test cases for Google Maps and Wear OS features across Agile sprint cycles",
      "Validated user stories and acceptance criteria against defined requirements",
      "Captured and analyzed device logs using ADB and USB debugging to diagnose issues, reproduce defects, and support root cause investigation",
      "Performed API testing using Postman and wrote Python and SQL scripts to validate request and response payloads, status codes, and backend data consistency",
      "Conducted usability and accessibility testing using assistive technologies including NVDA, JAWS, TalkBack, and VoiceOver, ensuring compliance with accessibility standards",
      "Tracked and managed defects in JIRA through the full lifecycle, from discovery to resolution verification, maintaining complete traceability",
      "Built Power BI dashboards to visualize test results, defect trends, and quality metrics, translating complex data into clear insights for engineering and product stakeholders",
      "Contributed to CI/CD validation processes supporting release readiness",
    ],
  },
  {
    role: "Fleet Response Specialist / Remote Assistance Dispatch (RAD)",
    org: "Waymo",
    location: "Austin, TX",
    period: "Aug 2018 — Nov 2019",
    bullets: [
      "Served as Remote Assistance Dispatcher for live, driverless Waymo autonomous vehicles, providing real-time human input and situational clarity to help vehicles interpret complex road environments and make safe operational decisions",
      "Built path solutions for stuck vehicles within the 3D-rendered vehicle environment, using MPT and multi-point trajectory construction around obstructions to safely restore autonomous operation",
      "Acted as on-shift point of contact for fleet escalations, monitoring driverless vehicle missions and intervening with precision guidance when autonomous systems encountered edge cases, ambiguous scenarios, or safety-critical situations",
      "Executed structured simulation scenarios and validation tests to expand autonomous vehicle operational capabilities, evaluating system responses and documenting outcomes",
      "Maintained rigorous accuracy, speed, and safety standards across all remote assistance interactions, operating in a fast-paced, safety-first environment where response quality directly impacted vehicle and public safety",
      "Recorded and tracked all escalations and driverless mission events accurately",
      "Supported staging, setup, and pre-mission checks to ensure vehicle readiness before engaging driverless operations",
      "Contributed to a pilot program monitoring human fatigue signs in drivers and co-pilots supervising autonomous vehicle operations, developing qualification criteria and annotated data to support AI training for operator safety and alertness detection",
      "Trained new Remote Assistance Dispatchers on operational procedures and escalation protocols",
    ],
  },
  {
    role: "Trust & Safety Quality Analyst / Data Validation Specialist",
    org: "YouTube (Google)",
    location: "Austin, TX",
    period: "Mar 2018 — Aug 2021",
    bullets: [
      "Performed large-scale quality analysis and validation of content moderation workflows, supporting enforcement of platform policies at global scale",
      "Analyzed moderation decisions and reviewer outputs to identify systemic quality gaps, policy edge cases, and patterns of inconsistent enforcement",
      "Conducted calibration and quality audits measuring accuracy, agreement rates, and reviewer drift to inform corrective actions",
      "Tracked and analyzed Trust & Safety performance metrics including accuracy, error rates, and escalation trends to surface emerging risks and improvement opportunities",
      "Partnered with policy, operations, and quality leadership to translate findings into actionable recommendations, contributing to guideline refinements and workflow improvements",
      "Documented defects, trends, and risk areas in JIRA, supporting continuous improvement initiatives and governance reviews",
      "Produced evidence-backed summaries and insights supporting decision-making by quality leads and program stakeholders",
    ],
  },
  {
    role: "Data Quality & Trust and Safety Specialist",
    org: "Apple Maps",
    location: "Austin, TX",
    period: "Jul 2017 — Oct 2017",
    bullets: [
      "Validated large-scale geospatial Points of Interest (POI) datasets supporting Apple Maps, ensuring data integrity, accuracy, and compliance with quality standards",
      "Analyzed structured and unstructured geospatial data to identify anomalies, inconsistencies, duplicates, and high-risk data patterns affecting user trust",
      "Designed and executed SQL-based validation and audit queries to surface systemic data quality issues across multi-source datasets",
      "Partnered with data engineering and quality teams to translate analytical findings into remediation strategies, improving dataset reliability",
      "Developed repeatable validation workflows and reporting artifacts that improved risk detection and data governance across regions",
      "Reduced manual review effort and improved quality signal detection through targeted automation and analytical checks",
    ],
  },
  {
    role: "Jr. Test Engineer, Mobile & Hardware QA",
    org: "Nexar Inc.",
    location: "San Francisco, CA",
    period: "Jul 2015 — Jan 2017",
    bullets: [
      "Designed and executed functional, regression, and scenario-based testing for AI-powered dash cameras and companion mobile apps on iOS and Android, ensuring stability, performance, and video data synchronization",
      "Validated video capture, playback integrity, and media transfer workflows across mobile and web interfaces",
      "Tested video performance under varying network conditions including Wi-Fi and mobile data to verify buffering behavior, upload reliability, and playback consistency",
      "Wrote and maintained Python scripts to build data-driven test utilities that simulated real-world video capture and connectivity scenarios, improving defect reproducibility",
      "Conducted detailed root cause analysis of video sync issues, frame drops, timestamp mismatches, and firmware-related playback anomalies",
      "Collaborated with development teams to reproduce streaming and upload defects, providing detailed logs and reproduction steps",
      "Integrated automated test execution into CI pipelines, increasing test coverage and accelerating validation cycles",
      "Reduced test cycle time by 25% through automation and structured test execution improvements",
    ],
  },
];
